# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QLocale, QMetaObject, QRect, QSize, Qt)
from PySide6.QtGui import (QAction, QFont)
from PySide6.QtWidgets import (QScrollArea, QLabel, QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QWidget, QAbstractScrollArea, QFrame)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(600, 600))
        MainWindow.setMaximumSize(QSize(800, 800))
        MainWindow.setMouseTracking(False)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionFit_to_window = QAction(MainWindow)
        self.actionFit_to_window.setObjectName(u"actionFit_to_window")
        self.actionNormal_size = QAction(MainWindow)
        self.actionNormal_size.setObjectName(u"actionNormal_size")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.centralwidget.setAutoFillBackground(False)
        self.label_help = QLabel(self.centralwidget)
        self.label_help.setObjectName(u"label_help")
        self.label_help.setGeometry(QRect(120, 20, 560, 50))
        font = QFont()
        font.setPointSize(12)
        self.label_help.setFont(font)
        self.label_help.setAlignment(Qt.AlignCenter)
        self.label_help.setMargin(-5)
        self.button_classify = QPushButton(self.centralwidget)
        self.button_classify.setObjectName(u"button_classify")
        self.button_classify.setGeometry(QRect(70, 80, 120, 40))
        self.button_classify.setBaseSize(QSize(0, 0))
        font1 = QFont()
        font1.setPointSize(10)
        self.button_classify.setFont(font1)
        self.button_classify.setStyleSheet(u"")
        self.button_classify.setIconSize(QSize(16, 16))
        self.button_classify.setProperty("isActivated", False)
        self.button_attack = QPushButton(self.centralwidget)
        self.button_attack.setObjectName(u"button_attack")
        self.button_attack.setGeometry(QRect(260, 80, 120, 40))
        self.button_attack.setFont(font1)
        self.button_attack.setProperty("isActivated", False)
        self.button_again = QPushButton(self.centralwidget)
        self.button_again.setObjectName(u"button_again")
        self.button_again.setGeometry(QRect(620, 80, 120, 40))
        self.button_again.setFont(font1)
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(190, 160, 440, 440))
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.label_image = QLabel()
        self.label_image.setObjectName(u"label_image")
        self.label_image.setEnabled(True)
        self.label_image.setGeometry(QRect(0, 0, 358, 358))
        self.label_image.setScaledContents(True)
        self.label_image.setProperty("isVisible", False)
        self.scrollArea.setWidget(self.label_image)
        self.button_add_noise = QPushButton(self.centralwidget)
        self.button_add_noise.setObjectName(u"button_add_noise")
        self.button_add_noise.setGeometry(QRect(440, 80, 125, 40))
        self.button_add_noise.setFont(font1)
        self.button_add_noise.setProperty("isActivated", False)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(120, 640, 560, 100))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_result = QLabel(self.frame)
        self.label_result.setObjectName(u"label_result")
        self.label_result.setGeometry(QRect(0, 0, 560, 100))
        self.label_result.setFont(font)
        self.label_result.setTextFormat(Qt.PlainText)
        self.label_result.setAlignment(Qt.AlignCenter)
        self.label_result.setProperty("isVisible", False)
        self.button_attack_untargeted = QPushButton(self.centralwidget)
        self.button_attack_untargeted.setObjectName(u"button_attack_untargeted")
        self.button_attack_untargeted.setGeometry(QRect(50, 170, 120, 40))
        self.button_attack_untargeted.setFont(font1)
        self.button_attack_untargeted.setProperty("isActivated", False)
        self.button_attack_least = QPushButton(self.centralwidget)
        self.button_attack_least.setObjectName(u"button_attack_least")
        self.button_attack_least.setGeometry(QRect(50, 350, 120, 40))
        self.button_attack_least.setFont(font1)
        self.button_attack_least.setProperty("isActivated", False)
        self.button_attack_random = QPushButton(self.centralwidget)
        self.button_attack_random.setObjectName(u"button_attack_random")
        self.button_attack_random.setGeometry(QRect(50, 260, 120, 40))
        self.button_attack_random.setFont(font1)
        self.button_attack_random.setProperty("isActivated", False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_help.raise_()
        self.button_attack.raise_()
        self.button_classify.raise_()
        self.button_again.raise_()
        self.scrollArea.raise_()
        self.button_add_noise.raise_()
        self.frame.raise_()
        self.button_attack_untargeted.raise_()
        self.button_attack_least.raise_()
        self.button_attack_random.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuView.addAction(self.actionFit_to_window)
        self.menuView.addAction(self.actionNormal_size)

        self.retranslateUi(MainWindow)
        self.button_again.clicked.connect(self.button_attack.show)
        self.button_again.clicked.connect(self.button_classify.show)
        self.button_again.clicked.connect(self.button_add_noise.show)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Adversarial Attacker", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionFit_to_window.setText(QCoreApplication.translate("MainWindow", u"Fit to window", None))
#if QT_CONFIG(shortcut)
        self.actionFit_to_window.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionNormal_size.setText(QCoreApplication.translate("MainWindow", u"Normal size", None))
        self.label_help.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Choose an image</span></p></body></html>", None))
        self.button_classify.setText(QCoreApplication.translate("MainWindow", u"Classify", None))
#if QT_CONFIG(shortcut)
        self.button_classify.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.button_attack.setText(QCoreApplication.translate("MainWindow", u"Attack", None))
#if QT_CONFIG(shortcut)
        self.button_attack.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.button_again.setText(QCoreApplication.translate("MainWindow", u"Recover", None))
#if QT_CONFIG(shortcut)
        self.button_again.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.label_image.setText("")
        self.button_add_noise.setText(QCoreApplication.translate("MainWindow", u"Add Noise", None))
#if QT_CONFIG(shortcut)
        self.button_add_noise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.label_result.setText("")
        self.button_attack_untargeted.setText(QCoreApplication.translate("MainWindow", u"Untarget", None))
#if QT_CONFIG(shortcut)
        self.button_attack_untargeted.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.button_attack_least.setText(QCoreApplication.translate("MainWindow", u"Least Likely", None))
#if QT_CONFIG(shortcut)
        self.button_attack_least.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.button_attack_random.setText(QCoreApplication.translate("MainWindow", u"Random target", None))
#if QT_CONFIG(shortcut)
        self.button_attack_random.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

